
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5001']
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:5002']
