filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata: ~
    - decode_json_fields:
        fields: ["message"]
        target: "json"
        overwrite_keys: true

- type: log
  enabled: true
  paths:
    - /user_logs/*.log
    - /product_logs/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: "message"
  fields:
    service_type: microservice
  fields_under_root: true
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 500
  multiline.timeout: 5s

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

# logging.json: true
logging.metrics.enabled: false
logging.to_stderr: true
logging.level: info
logging.to_files: false