
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    ports:
      - "5432:5432"

  user_service:
    build: ./user-service
    environment:
      DATABASE_URL: postgresql://user_service:userpassword@postgres/user_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: your_secret_key
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis

  product_service:
    build: ./product-service
    environment:
      DATABASE_URL: postgresql://product_service:productpassword@postgres/product_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - user_service
      - redis

  frontend:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - user_service
      - product_service

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - promdata:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    volumes:
      - grafdata:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  pgdata:
  promdata:
  grafdata:
