
services:
  # database service
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # enable monitoring
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
      # add custom config for monitoring
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"

  # backend monitoring
  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
    ports:
      - "9187:9187"
    environment:
    - DATA_SOURCE_NAME=postgresql://monitoring:monitoringpassword@postgres:5432/postgres?sslmode=disable    
    depends_on:
      - postgres
    command:
      - "--web.listen-address=:9187"
      - "--web.telemetry-path=/metrics"
      - "--log.level=info"
      - "--auto-discover-databases"

  # backend service
  user_service:
    build: ./user-service
    environment:
      DATABASE_URL: postgresql://user_service:userpassword@postgres/user_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: mysecretkey
      LOG_LEVEL: INFO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis

  product_service:
    build: ./product-service
    environment:
      DATABASE_URL: postgresql://product_service:productpassword@postgres/product_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_LEVEL: INFO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - user_service
      - redis

  # frontend service
  frontend:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - user_service
      - product_service

  # caching service
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # monitoring service
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - promdata:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - postgres_exporter

  # monitoring service
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    volumes:
      - grafdata:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus




# volumes
volumes:
  pgdata:
  promdata:
  grafdata:
