services:
  
  frontend:
    build: ./frontend-service
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - user-service
      - product-service
  
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:1234567890@localhost/webapp
    depends_on:
      - db
    networks:
      - app-net

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://postgres:1234567890@localhost/webapp
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
